# permissions for end users to view podcleanupconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podcleanupconfig-viewer-role
rules:
- apiGroups:
  - core.craftdemo.com
  resources:
  - podcleanupconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.craftdemo.com
  resources:
  - podcleanupconfigs/status
  verbs:
  - get
