# permissions for end users to edit podcleanupconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podcleanupconfig-editor-role
rules:
- apiGroups:
  - core.craftdemo.com
  resources:
  - podcleanupconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.craftdemo.com
  resources:
  - podcleanupconfigs/status
  verbs:
  - get
